apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          # 여러분의 image 주소를 입력해주세요.
          image: krmp-d2hub-idock.9rum.cc/dev-test/repo_9dc097d08885
      env:
        - name: VITE_TEST_FIRST
          valueFrom:
            configMapKeyRef:
              name: test-cm
              key: cm1
                      - name: VITE_TEST_SECOND
          valueFrom:
            configMapKeyRef:
              name: test-cm
              key: cm2
                      - name: VITE_TEST_THRID
          valueFrom:
            configMapKeyRef:
              name: test-cm
              key: cm3