const COUNTRIES = Object.freeze([
  { id: 1, name: "United States" },
  { id: 2, name: "Canada" },
  { id: 3, name: "United Kingdom" },
  { id: 4, name: "Australia" },
  { id: 5, name: "Germany" },
  { id: 6, name: "France" },
  { id: 7, name: "Japan" },
  { id: 8, name: "China" },
  //   { id: 9, name: "South Korea" },
  { id: 10, name: "India" },
  { id: 11, name: "Brazil" },
  { id: 12, name: "Mexico" },
  { id: 13, name: "Russia" },
  { id: 14, name: "South Africa" },
  { id: 15, name: "Italy" },
  { id: 16, name: "Spain" },
  { id: 17, name: "Sweden" },
  { id: 18, name: "Norway" },
  { id: 19, name: "Netherlands" },
  { id: 20, name: "Switzerland" },
  { id: 21, name: "Belgium" },
  { id: 22, name: "Argentina" },
  { id: 23, name: "Chile" },
  { id: 24, name: "Singapore" },
  { id: 25, name: "Malaysia" },
  { id: 26, name: "New Zealand" },
  { id: 27, name: "United Arab Emirates" },
  { id: 28, name: "Saudi Arabia" },
  { id: 29, name: "Israel" },
  { id: 30, name: "Ireland" },
]);

export default COUNTRIES;
