const COUNTRY = [
  { id: 1, name: "Australia", code: "AU" },
  { id: 2, name: "Argentina", code: "AR" },
  { id: 3, name: "Brazil", code: "BR" },
  { id: 4, name: "Canada", code: "CA" },
  { id: 5, name: "China", code: "CN" },
  { id: 6, name: "France", code: "FR" },
  { id: 7, name: "Germany", code: "DE" },
  { id: 8, name: "India", code: "IN" },
  { id: 9, name: "Indonesia", code: "ID" },
  { id: 10, name: "Italy", code: "IT" },
  { id: 11, name: "Japan", code: "JP" },
  { id: 12, name: "Mexico", code: "MX" },
  { id: 13, name: "Russia", code: "RU" },
  { id: 14, name: "South Africa", code: "ZA" },
  { id: 15, name: "Spain", code: "ES" },
  { id: 16, name: "United Kingdom", code: "GB" },
  { id: 17, name: "United States", code: "US" },
  { id: 18, name: "Turkey", code: "TR" },
  { id: 19, name: "Thailand", code: "TH" },
  { id: 20, name: "Switzerland", code: "CH" },
  { id: 21, name: "Sweden", code: "SE" },
  { id: 22, name: "Saudi Arabia", code: "SA" },
  { id: 23, name: "Portugal", code: "PT" },
  { id: 24, name: "Poland", code: "PL" },
  { id: 25, name: "Norway", code: "NO" },
  { id: 26, name: "Netherlands", code: "NL" },
  { id: 27, name: "Malaysia", code: "MY" },
  { id: 28, name: "Greece", code: "GR" },
  { id: 29, name: "Egypt", code: "EG" },
  { id: 30, name: "Denmark", code: "DK" },
  { id: 31, name: "Czech Republic", code: "CZ" },
  { id: 32, name: "Chile", code: "CL" },
  { id: 33, name: "Belgium", code: "BE" },
  { id: 34, name: "Austria", code: "AT" },
  { id: 35, name: "Vietnam", code: "VN" },
  { id: 36, name: "Ukraine", code: "UA" },
  { id: 37, name: "Taiwan", code: "TW" },
  { id: 38, name: "Singapore", code: "SG" },
  { id: 39, name: "New Zealand", code: "NZ" },
  { id: 40, name: "Israel", code: "IL" },
  { id: 41, name: "Ireland", code: "IE" },
  { id: 42, name: "Hungary", code: "HU" },
  { id: 43, name: "Hong Kong", code: "HK" },
  { id: 44, name: "Finland", code: "FI" },
  { id: 45, name: "Philippines", code: "PH" },
  { id: 46, name: "Pakistan", code: "PK" },
  { id: 47, name: "Nigeria", code: "NG" },
];

export default COUNTRY;
